// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for GameID.
const (
	Check           GameID = "check"
	Crash           GameID = "crash"
	Crashm          GameID = "crashm            |"
	PhMoneyrocket97 GameID = "ph_moneyrocket_97"
	PhSlimbo97      GameID = "ph_slimbo_97"
)

// BetIsAlreadyActiveError defines model for BetIsAlreadyActiveError.
type BetIsAlreadyActiveError = ErrorResponse

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details string `json:"details"`
	Message string `json:"message"`
}

// GameID defines model for GameID.
type GameID string

// GameSession defines model for GameSession.
type GameSession struct {
	GameUrl string `json:"game_url"`
}

// User defines model for User.
type User struct {
	// Country Country code ISO 3166-1
	Country   *string `json:"country,omitempty"`
	Firstname *string `json:"firstname,omitempty"`

	// Id User's ID (external)
	Id       string  `json:"id"`
	Lastname *string `json:"lastname,omitempty"`
	Nickname *string `json:"nickname,omitempty"`
}

// UserBalance defines model for UserBalance.
type UserBalance struct {
	// Amount The amount of balance in currency cents.
	Amount int64 `json:"amount"`

	// Currency The currency code in ISO4217.
	Currency string `json:"currency"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4RSYW/TMBD9K9aBBEjpqsLUiXzbGEL9NInBp2mqXOeSmNpnc3bQopL/jpyszVgy6Jc6",
	"fr537727AyhnvSOkGCA/QFA1WtkfrzBuwqVhlEV7qaL+hZ+ZHSdIGnNTQn53gNeMJeTwajnSLB85lv3z",
	"rxi8o4DQ3XcZ/H2VH8Cz88hRY9+ywCi16Y+x9Qg5hMiaKugysBiCrHAG6zJg/NloxgLyu9PD7ER3nx1L",
	"3O4HqpjovkiLm+vEhtTYVKdqVHvIQLEM9fHfiie/35CBr7fBaLtz248Xw6d1hC07tceY7sZmo/bU7BZD",
	"0I6mpitpcduw+b+z08s5Q98D8pRcuYYit0O4QbH2sRcBnwZAKFeg2NzeiA+r9Xqxghn1peYQSVqcnYsu",
	"puRJy5sgNtfiLT5EZJLm3Ryzkf8gJq32L4DPctHFi4lcSSNJzayatCmAqfRvNYoBE64Uu6FcaBKqYUZS",
	"rVBpyc9GO5oiVsiQwcOicovxdn2eVBzr5luNrGkOmtIozt+vLs6mcT0z/WjgSYNpBqlGU+kgp8aYDJxH",
	"kl5DDml1ZazDgHR/AgAA//8V1iVPBwQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
